# Generated by Django 4.2.2 on 2023-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Live",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Test", models.CharField(default="", max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Live Stream",
                "verbose_name_plural": "Live",
            },
        ),
        migrations.CreateModel(
            name="RedditCrawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SubReddit_Name", models.CharField(default="", max_length=200)),
                ("Title", models.CharField(default="", max_length=300)),
                ("Posted_By", models.CharField(default="", max_length=300)),
                ("Author_id", models.CharField(default="", max_length=30)),
                ("Date", models.CharField(default="", max_length=20)),
                ("Comment_Log", models.TextField(default="")),
                ("Content", models.TextField(default="")),
                ("Upvote", models.CharField(default="", max_length=20)),
                ("Search_Start", models.DateTimeField(verbose_name="Start Time")),
                (
                    "Search_Finished",
                    models.DateTimeField(auto_now_add=True, verbose_name="Finish Time"),
                ),
                ("Post_Link", models.TextField(default="")),
                ("Post_id", models.CharField(default="", max_length=30, unique=True)),
                ("Post_image", models.ImageField(default="", upload_to="screenshot/")),
                ("Comment_image", models.ImageField(default="", upload_to="images/%y")),
            ],
            options={
                "verbose_name": "Crawls",
                "verbose_name_plural": "Crawl SubReddit",
            },
        ),
        migrations.CreateModel(
            name="VictimList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Subreddit",
                    models.CharField(default="", max_length=100, unique=True),
                ),
                ("Total_Crawl", models.PositiveIntegerField(default=0)),
                ("Last_Crawl", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SubReddits for Crawling Service",
                "verbose_name_plural": "Victim List",
            },
        ),
    ]
